### ISSUE TITLE
HTML/Markdown in checkboxes labels

### ISSUE THREAD

**Issue by gerritvanaaken** [tobimori/kirby-dreamform#77] opened 2024-07-26 08:16 UTC
Would it be possible to habe (at least) links working within the checkbox label? See screenshot. That would be super handy for a lot of people, I guess.

<img width="561" alt="Bildschirmfoto 2024-07-26 um 10 15 07" src="https://github.com/user-attachments/assets/c8f37b65-6f45-4a4e-a93c-126ae1575f10">

**Comment by tobimori** [comment] 2024-07-26 10:46
duplicate of #57

**Closed as completed by tobimori** 2024-07-26 10:46 UTC
